name: Deploy a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Surge.sh
        run: npm install -g surge

      - name: Desplegar a Surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge --project ./ --domain dacarloslora.surge.sh --token $SURGE_TOKEN
